### ISSUE TITLE
[Funding]: 1st Nix Learning Group Bochum 2023-10-19

### ISSUE THREAD

**Issue by katexochen** [NixOS/foundation#100]
### Event Name

Nix Learning Group Bochum

### Event Website

https://github.com/nix-community-bochum/nix-learning-group

### Event Purpose

We want to establish a recurring Nix/NixOS learning group at the Ruhr-University Bochum. The goal is to especially attract the interest from students in CS/Applied CS/IT Security programs and to provide a space to get started using Nix/NixOS. The event is open to non-student people, too. 
The meeting is a place to tell each other about current projects and finding together to help each other and hack together.

### Event Visitors

10-15

### Event Organizer

Paul Meyer, Moritz Sanft

### Budget amount

200€

### Budget description

Food and drinks

**Comment by refroni** [comment]
approved

**Comment by msanft** [comment]
Hey, is there a regular reviewing schedule for the expenses, or do we explicitly need to list them somewhere else to be reviewed?

https://opencollective.com/nixos/expenses/167601

**Comment by katexochen** [comment]
@refroni @zimbatm any update on the expense review?

**Comment by edolstra** [comment]
@katexochen Sorry about that, I'll take care of it.
