### ISSUE TITLE
[Funding]: ThaigerSprint.org 15-22 Feb 2024

### ISSUE THREAD

**Issue by DavHau** [NixOS/foundation#108]
### Event Name

Thaiger Sprint

### Event Website

https://thaigersprint.org

### Event Purpose

The Thaiger Sprint is a week-long event focused on Nix, aiming to bring together about 20 developers in Chiang Mai, Thailand. Scheduled from February 15-22, 2024, its purpose is to facilitate intensive hacking sessions, collaboration, and knowledge sharing among Nix enthusiasts. The event includes catered meals and a diverse range of proposed topics for development and discussion. It seeks to foster community engagement, contribute to the Nix ecosystem, and provide an immersive, collaborative environment for developers. For more details, visit the [Thaiger Sprint website](https://thaigersprint.org/).

### Event Visitors

20

### Event Organizer

David Hauer

### Budget amount

2500 EUR

### Budget description

The budget for the Thaiger Sprint would primarily enable the organization of this intensive Nix development event. It will cover essential expenses such as venue rental in Chiang Mai, catering services for the participants, and necessary technical equipment. Additionally, the budget will help in providing necessary support for activities and sessions planned during the event.

**Comment by edolstra** [comment]
Just to be sure, what's the currency for that 2500?

**Comment by DavHau** [comment]
Oh, I meant EUR.

**Comment by DavHau** [comment]
If possible, it would be great if we could receive the funds in advance via https://opencollective.com/thaigersprint.
The event starts on Thursday.

**Comment by kpark955** [comment]
@DavHau Hi, the funds were sent yesterday. Let me know if you encounter any issues receiving this.
