### ISSUE TITLE
[Funding]: 4th SoCal Nix User Group Meetup 1/25/2024

### ISSUE THREAD

**Issue by davidnuon** [NixOS/foundation#114]
### Event Name

4th SoCal Nix User Group Meetup

### Event Website

https://socal-nug.com/events/2024-01-25/

### Event Purpose

Southern California Nix User Group's 4th meeting that took place 2024-01-25 in Signal Hill, CA

### Event Visitors

15

### Event Organizer

David Nuon

### Budget amount

231.47 USD

### Budget description

Purchase of food for the event

**Comment by edolstra** [comment]
Thanks, approved!

**Comment by zimbatm** [comment]
Make sure to keep a copy of the invoice so you can submit it to https://opencollective.com/nixos/expenses/new for reimbursement. In the comments, add a link back to the issue so we can track it more easily.
