### ISSUE TITLE
[Funding]: Nix(OS) Learning Group Bochum 2024-02-22

### ISSUE THREAD

**Issue by katexochen** [NixOS/foundation#116]
### Event Name

Nix(OS) Learning Group Bochum

### Event Website

https://github.com/nix-community-bochum/nix-learning-group

### Event Purpose

We want to establish a recurring Nix/NixOS learning group at the Ruhr-University Bochum. The goal is to especially attract the interest from students in CS/Applied CS/IT Security programs and to provide a space to get started using Nix/NixOS. The event is open to non-student people, too.
The meeting is a place to tell each other about current projects and finding together to help each other and hack together.

The upcoming meetup is our 4th event. More than 25 people participated in each of the previous events, with more than 50% of participants who hadn't had contact to Nix before. 

### Event Visitors

~25

### Event Organizer

Paul Meyer, Moritz Sanft

### Budget amount

200€

### Budget description

Food and drinks.

**Comment by edolstra** [comment]
Thanks, approved!

**Comment by zimbatm** [comment]
Make sure to keep a copy of the invoice so you can submit it to https://opencollective.com/nixos/expenses/new for reimbursement. In the comments, add a link back to the issue so we can track it more easily.

**Comment by msanft** [comment]
Thanks all! Submitted the expense [here](https://opencollective.com/nixos/expenses/189376).
