### ISSUE TITLE
[Funding]: NixOS meetup Dresden 29th Feb 2024

### ISSUE THREAD

**Issue by mcnesium** [NixOS/foundation#120]
### Event Name

NixOS meetup Dresden

### Event Website

https://www.club-haengemathe.de/2024/02/29/nix-meetup.html

### Event Purpose

Gather different parties that are interested in NixOS in Dresden, Germany. Exchange/discuss ideas, build community.

### Event Visitors

10

### Event Organizer

mcnesium

### Budget amount

150€

### Budget description

Pizza and drinks

**Comment by edolstra** [comment]
Thanks, approved!

**Comment by zimbatm** [comment]
Make sure to keep a copy of the invoice so you can submit it to https://opencollective.com/nixos/expenses/new for reimbursement. In the comments, add a link back to the issue so we can track it more easily.
