### ISSUE TITLE
[Funding]: Munich meetup 2024-02-10

### ISSUE THREAD

**Issue by lheckemann** [NixOS/foundation#123]
### Event Name

Munich NixOS meetup

### Event Website

https://discourse.nixos.org/t/nixos-meetup-munich-friday-2024-02-09/39074

### Event Purpose

Talking about Nix and NixOS, informing the Nix-curious, hacking together

### Event Visitors

18

### Event Organizer

@lheckemann

### Budget amount

€150

### Budget description

Get food for everyone to share!

**Comment by edolstra** [comment]
Thanks, approved!

**Comment by zimbatm** [comment]
Make sure to keep a copy of the invoice so you can submit it to https://opencollective.com/nixos/expenses/new for reimbursement. In the comments, add a link back to the issue so we can track it more easily.
