### ISSUE TITLE
[Funding]: BruNix - March 11th 2024

### ISSUE THREAD

**Issue by yvan-sraka** [NixOS/foundation#124]
### Event Name

First Brussels Nix User Group Meeting

### Event Website

https://brunix.glitch.me/

### Event Purpose

We are bootstrapping a monthly meeting for Belgian Nix Users! Below is the description of the Meetup from the web page:

> Nix enthusiasts of all levels are encouraged to join; this includes those merely curious about Nix. Introductory sessions and support will be available for beginners — don't forget your laptop!
> 
> For those interested in presenting to the group, please inform [Michael](mailto:neo@hacktheplanet.be) or [Yvan](https://functional.cafe/@yvan) in advance so they can organize and promote the sessions. We're looking for lightning talks of up to 10 minutes. Although not obligatory, giving us a heads-up about your presentation is appreciated, especially since scheduled talks will take precedence if we're pressed for time.
> 
> The meetup will start with any scheduled presentations, followed by pizza! Post-meal, we'll engage in some casual hacking and networking. We'll also have the option to continue the discussion over a beer at BrewDog for those interested.
> Contact
> 
> Join us in our [Matrix group](https://matrix.to/#/#brunix:hacktheplanet.be).

### Event Visitors

10-20

### Event Organizer

Yvan Sraka

### Budget amount

200 EUR

### Budget description

Buy pizzas for 10–20 participants :)

**Comment by edolstra** [comment]
Thanks, approved!

Make sure to keep a copy of the invoice so you can submit it to https://opencollective.com/nixos/expenses/new for reimbursement. In the comments, add a link back to the issue so we can track it more easily.
