### ISSUE TITLE
3 month plan 

### ISSUE THREAD

**Issue by domenkozar** [NixOS/foundation#13]
- NixOS/nix.dev#7 NixOS/nix.dev#8 NixOS/nix.dev#9 @edolstra 
- NixOS/nix.dev#11 @armijnhemel 
- hire an admin person @?
- Infra team & s3 bucket migration @?
- increasing donations to the foundation with sponsorship plans @?
- NixOS/nix.dev#14 @armijnhemel 
- Project wide roadmap @everyone
- NixOS/nix.dev#12: Team empowerment @refroni

**Comment by fricklerhandwerk** [comment]
Here are issues the documentation team encountered which only the board can address to unblock some of our tasks.

https://github.com/NixOS/nix.dev/issues/277
https://github.com/NixOS/nix.dev/issues/287
https://github.com/NixOS/nixos-homepage/pull/882

These issues should be migrated to this repository to make use of our paper trail on existing discussions, but I don't have permissions to do that.
