### ISSUE TITLE
[Funding]: BruNix - April 8th 2024

### ISSUE THREAD

**Issue by yvan-sraka** [NixOS/foundation#130]
### Event Name

Second Brussels Nix User Group Meeting

### Event Website

https://brunix.glitch.me/

### Event Purpose

We're running a 2nd iteration ([issue to the previous one](https://github.com/NixOS/foundation/issues/124)) of our monthly meeting for Belgian Nix Users! Below is the description of the Meetup from the web page:

> Nix enthusiasts of all levels are encouraged to join; this includes those merely curious about Nix. Introductory sessions and support will be available for beginners — don't forget your laptop!
> 
> For those interested in presenting to the group, please inform [Michael](mailto:neo@hacktheplanet.be) or [Yvan](https://functional.cafe/@yvan) in advance so they can organize and promote the sessions. We're looking for lightning talks of up to 10 minutes. Although not obligatory, giving us a heads-up about your presentation is appreciated, especially since scheduled talks will take precedence if we're pressed for time.
> 
> The meetup will start with any scheduled presentations, followed by pizza! Post-meal, we'll engage in some casual hacking and networking. 
>
> Contact
> 
> Join us in our [Matrix group](https://matrix.to/#/#brunix:hacktheplanet.be).

### Event Visitors

10-20

### Event Organizer

Yvan Sraka

### Budget amount

200

### Budget description

Buy pizzas for 10–20 participants :)

**Comment by edolstra** [comment]
Approved ✔️ Make sure to refer to this issue when submitting the expense to https://opencollective.com/nixos/expenses/new
