### ISSUE TITLE
[Funding]: 5th SoCal Nix User Group Meetup April 13th, 2024 

### ISSUE THREAD

**Issue by davidnuon** [NixOS/foundation#132]
### Event Name

5th SoCal Nix User Group Meetup 

### Event Website

https://socal-nug.com/events/2024-04-13/

### Event Purpose

Southern California Nix User Group's 5th meeting that will take place 2024-04-13 in Long Beach, CA at the [Long Beach City College](https://www.lbcc.edu/)

### Event Visitors

25

### Event Organizer

David Nuon

### Budget amount

127.41 USD

### Budget description

Refreshments for the attendees

**Comment by edolstra** [comment]
Approved ✔️ Make sure to refer to this issue when submitting the expense to https://opencollective.com/nixos/expenses/new
