### ISSUE TITLE
[Funding]: New York Nix Users Group Meetup May 9th

### ISSUE THREAD

**Issue by twitchy0** [NixOS/foundation#152]
### Event Name

New York Nix Users Group Meetup

### Event Website

https://www.meetup.com/new-york-nix-users-group/

### Event Purpose

The new york nix users group is a meetup group for the open source technology and ecosystem for nixpkgs, nix, and nixos. We meet to grow the community, share knowledge and ideas, and collaborate on open source projects.

The meetup is typically discussions around the technology, onboarding new users, brief talks/demos, debugging a problem someone is facing, and collaborating on a project.

### Event Visitors

22

### Event Organizer

Nitin Passa

### Budget amount

304.87

### Budget description

Event Catering: drinks and food.

**Comment by edolstra** [comment]
Approved ✔️ Make sure to refer to this issue when submitting the expense to https://opencollective.com/nixos/expenses/new
