### ISSUE TITLE
rsync.net account for backup of the hydra database

### ISSUE THREAD

**Issue by mweinelt** [NixOS/foundation#159]
The infra team wants an [rsync.net](http://rsync.net/) account for backups of the [hydra.nixos.org](http://hydra.nixos.org/) database. This was previously in place, but paid by Graham.

We'd need roughly 2 TB of storage, which would incur about [25 USD/month](https://www.rsync.net/signup/order.html).

Can the foundation decide on that, and then have someone help me create the account (wrt to ownership and payment)?

**Comment by zimbatm** [comment]
To get things going, I ordered:

```
size: 2 TB
redundancy: standard
region: Zurich (closest to Hetzner)
pricing: $259.20 billed annually (so I only have to get one invoice refunded)
```

With special price: $192.00

Added to Bitwarden.

I will submit this to Open Collective, and the foundation can decide whether to reimburse me. If not, no harm, no foul.

**Comment by zimbatm** [comment]
https://opencollective.com/nixos/expenses/208838

**Comment by mweinelt** [comment]
As @vcunat found out, our account is apparently not able to use `zfs send`. Those accounts are different product with a minimum order of 5TB.

@zimbatm Can you check with rsync.net whether we can migrate into that instead? The price is more like 650 USD/yr.

**Comment by zimbatm** [comment]
thanks to vcunat for reaching out to rysnc.net, and rsync for enabling zfs send on our current plan.

that means we're keeping our current this plan.

**Comment by edolstra** [comment]
Thanks, will take care of the expense.

**Comment by vcunat** [comment]
The expense is a recurrent one, from a credit card, so... we need some plan for that?

**Comment by zimbatm** [comment]
I don't mind recording the expense on opencollective if the invoice is once a year. If it's more frequency, @refroni please give me a credit card to add on their file.
