### ISSUE TITLE
[Funding] Editorial work on documentation to help reduce cache load

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/foundation#162]
At the time of writing the [Nix documentation project Open Collective](https://opencollective.com/nixos/projects/documentation-project) has 7500 EUR left. Following the latest [discussion on enabling more people to host their own cache](https://discourse.nixos.org/t/2024-06-06-re-long-term-s3-cache-solutions-meeting-minutes-6/46617/4), I would [spend 5000 EUR on a technical writer](https://discourse.nixos.org/t/technical-writer-for-nix-documentation/48739) to come up with the appropriate tutorials.

This needs reviews and guidance to ensure the quality standards we're used to. Because it would be weird to pay myself from the budget I'm managing on behalf of the foundation, I'm hereby asking the foundation board to support my editorial work on that effort with up to 2000 EUR from that same Open Collective documentation fund.

The deliverable is to complete and merge the three tutorials listed in the job posting, including all related tasks and communication around the results.

**Comment by refroni** [comment]
@fricklerhandwerk can you clarify the usage of the funds - 
What's the hourly rate? How many hours do you believe the project will take?
If I understand correctly you are asking to hire a technical writer and also yourself as editor separately?

**Comment by refroni** [comment]
Approved.
