### ISSUE TITLE
Get the foundation's admin assistant access to accounts

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/foundation#163]
Currently only @edolstra has sole access to most of the foundation's resources. This has proven a source of friction multiple times over around Summer of Nix, where we regularly need to process numerous invoices. And regardless, there are plans to [pass on responsibilities](https://discourse.nixos.org/t/nixos-foundation-board-giving-power-to-the-community/44552#eelco-steps-down-from-the-board-1). The foundation's assistant has been working very reliably with us since end of 2023, therefore I propose to enable her to issue payments on all platforms.
 
I recently met with @edolstra to collect the current accounts:
- [Bunq](https://www.bunq.com/) bank account
    - access requires EU citizenship
    - there are no account limits, ideally only president and treasurer should have access - this should be discussed
    - account owner needs to invite someone
    - need to install the app
    - switching the bank may be difficult
        - An anti-money-laundering legislation increased costs of doing checks
        - the foundation was not profitable for the last bank, and suspicious because we’re receiving a lot of international payments
        - security checks with a new bank may take on the order of weeks or months
        - the situation may be different now that the foundation has more money
- [e-boekhouden](https://www.e-boekhouden.nl/) (accounting system)
- [PayPal](https://www.paypal.com/)
- [Stripe](https://stripe.com)
- [Wise](https://wise.com/)
- [Open Collective](https://opencollective.com/nixos)
- [eHerkenning](https://www.eherkenning.nl/) / [Reconi](https://www.reconi.nl/)
  - eHerkenning is single sign-on with the Dutch government for organisations
  - there are multiple providers, one of them is Reconi
  - needed for submitting tax reports to the the Belastingdienst (Dutch Tax authority).
  - requires minimal level 3 eHerkenning
  - responsibility transfer would require registering with Reconi and getting authorised for/by the foundation to submit reports

**Comment by refroni** [comment]
Kate has access and we are working more. Will close the issue for now unless we need more.
There's going to be more effort to generally be able to work with a banking system that is not as enclosed.

**Comment by fricklerhandwerk** [comment]
I'm not sure this is actually closed. Does someone else then @edolstra have access to all the other accounts?

**Comment by fricklerhandwerk** [comment]
Feedback from @edolstra on systematising our accounting system:

Whatever we would use in the future, it should ideally:

1) be able to prepare/submit intra-EU VAT ([BTW](https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/btw/btw), [ICP](https://www.belastingdienst.nl/wps/wcm/connect/bldcontenten/belastingdienst/business/vat/vat_in_the_netherlands/filing_vat_return_and_paying_vat/filing_a_vat_return/statement_of_intra_community_services/)) declarations; 

2) be able to deal with the BTW situation for stichtingen (e-boekhouden doesn't); 

3) have Bunq/Stripe/PayPal integration (e-boekhouden only has Bunq); 

4) be able to track [one-stop-shop EU VAT](https://vat-one-stop-shop.ec.europa.eu/index_en) (not super important since we only do that for NixCon)
