### ISSUE TITLE
[Funding]: NixOS meetup Dresden 15 Oct 2024

### ISSUE THREAD

**Issue by mcnesium** [NixOS/foundation#170]
### Event Name

NixOS meetup Dresden

### Event Website

https://www.club-haengemathe.de/2024/10/15/nix-meetup.html

### Event Purpose

Gather different parties that are interested in NixOS in Dresden, Germany. Exchange/discuss ideas, build community.

### Event Visitors

10

### Event Organizer

mcnesium

### Budget amount

150€

### Budget description

Pizza and drinks

**Comment by edolstra** [comment]
Approved, please file an expense afterwards on https://opencollective.com/nixos/expenses.
