### ISSUE TITLE
Hydra short-term transition plan proposal

### ISSUE THREAD

**Issue by mweinelt** [NixOS/foundation#176]
With the Equinix Metal sponsorship coming to and end around EOY we need to take steps to keep our build pipelines working, so that we can keep delivering package and channel updates to our users.

To that end, as a short-term measure, I propose to rent an adequate number of machines from Hetzner, which in a comparison with other popular hosters (e.g. OVH, Scaleway) seems to be among the most cost-effective options. 

The plan is for this to be a transitional period, while we investigate going for our own bare metal machines, that we plan to host with various sponsors.

## Replace hydra builders

The proposal is to replace the two ARM64 builders with similar machines, so that we can keep the number of ARM64 builders at three. For x86_64 I propose we rent four machines, since we regularly provide x86_64-linux build capacity to test bulk updates for bigger changesets and package set updates.

- 2x [RX220](https://www.hetzner.com/dedicated-rootserver/rx220/configurator/#/) (Ampere Q80-30, 256 GB DDR4) ~270 EUR/mo
    - we already have one of these at Hetzner
    - Planned capacity: 80 build slots with 2 cores, 4 big-parallel build slots with 20 cores
- 4x [AX162-R](https://www.hetzner.com/dedicated-rootserver/ax162-r/configurator/#/) (AMD Epyc 9454P, 48C/96T, 256 GB DDR5) ~240 EUR/mo
    - Planned capacity: 144 build slots with 2 cores, 4 big-parallel build slots with 24 cores

Total: 1500 EUR/mo + 600 EUR setup cost

## Upgrade for hydra.nixos.org

On top of this comes a required update for rhea.nixos.org, the machine that hosts hydra, which we already host at Hetzner. It is currently bottlenecked by the compression load of incoming build results and cannot go any faster. Additionally, it [requires more RAM](https://grafana.nixos.org/goto/jEdu9w7NR?orgId=1) to effectively deal with evaluations, for which we currently extensively rely on [`zramSwap`](https://github.com/NixOS/infra/commit/b349b94c650e803cce59cbf9f0fdfb935db4cef0).

- 1x [AX162-R](https://www.hetzner.com/dedicated-rootserver/ax162-r/configurator/#/) (upgrade from existing AX101) ~240 EUR/mo
    - up from 32 to 96 parallel receive/compression slots
    - up from 128 to 256GB RAM for evals

Total: 240 EUR/mo (up from 107 EUR/mo) and 100 EUR setup cost

**Comment by refroni** [comment]
Very much approved.

Shoutout again to you, the infra team and all involved for getting this together <3
