### ISSUE TITLE
Finish the transfer of nix.dev

### ISSUE THREAD

**Issue by zimbatm** [NixOS/foundation#42]
It would be good to finish the transfer of ownership of nix.dev to the foundation and the documentation team. I noticed some uncertainty because the documentation is halfway in the org, but still contains the copyright notice to Domen. I suppose that documentation team members want to know that their work is held in good hands.

@domenkozar, what are the requirements on your side for this to happen?

**Comment by zimbatm** [comment]
Please find attached the transfer agreement for review by both parties: https://nixos-foundation.notion.site/nix-dev-Coypright-Transfer-Agreement-9d361432ce6845eeb12b75714ed417e3

**Comment by domenkozar** [comment]
There are no requirements from my side, we can proceed!

**Comment by zimbatm** [comment]
The agreement was signed. Missing are:
* [ ] Cloudflare - depends on #75 
* [ ] Domain - depends on #50

**Comment by fricklerhandwerk** [comment]
This is done and can be closed.
