### ISSUE TITLE
Set up a credentials scheme for the marketing team

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/foundation#49]
The [Nix marketing team](https://nixos.org/community/teams/marketing) needs a way to handle credentials to the various communication channels they work with.

Specifically and immediately, the team needs
- credentials to access `webmaster@nixos.org`
- to set up `marketing@nixos.org`
- a way to add team members and set forwarders/aliases

Generally, the marketing team (and supposedly other teams in the future) needs
- a predictable scheme of obtaining and handling credentials
- a process for creating or claiming accounts on communication platforms
- a way to keep track of who has access to what.

This was discussed with @garbas and @tomberek on the Nix marketing meeting 2023-03-15.

**Comment by garbas** [comment]
For now I've setup the 1password vault on my personal account so that we are not blocked on this, but it would be nice to use whatever the solution is also used with other teams.

**Comment by zimbatm** [comment]
Two weeks based on the current rate of changes.  https://github.com/NixOS/foundation/issues/58 could happen first.

**Comment by thufschmitt** [comment]
Is that still an issue?

**Comment by zimbatm** [comment]
No, everybody has access to Bitwarden now
