### ISSUE TITLE
Move domains to Gandi

### ISSUE THREAD

**Issue by zimbatm** [NixOS/foundation#50]
At the moment nixos.org is held by @edolstra at
https://www.united-domains.de/ . Any objections to moving it to a shared account that is held by the foundation? Gandi has been providing domains for the nix-community org so I'm sure they would be up for it.

**Comment by samueldr** [comment]
I don't have any opinion.

I'm just leaving this relevant thread I saw a few days ago about gandi:

 - https://lobste.rs/s/flcpop/what_domain_registrar_is_worth_using

> Gandi, one of the best hosts in Europe, has been [bought by a not particularly great company](https://www.boursorama.com/bourse/actualites/montefiore-investment-cede-sa-participation-dans-gandi-a-total-webhosting-solutions-9b745e53ac6bbe21fac2f4f3a3eff0a0) (known for price gouging and bad customer service). All my domains are registered with Gandi, so I’m looking to move somewhere else, and I know I’m not the only one, and I have very little appetite for GoDaddy or 101domain or other lumbering dinosaurs who are just as bad as Gandi is probably now going to become. Since Google results for this sort of thing are mostly spam these days, I thought I’d ask here – I hope it’s not considered off topic to ask.

**Comment by zimbatm** [comment]
This is mostly FUD or overreaction. Gandi is still the best host in Europe. We know somebody on the inside so we will be notified in advance if things start to change.

**Comment by thufschmitt** [comment]
/cc @NixOS/infra since I guess that's relevant to them :)
I think that could also be an occasion for migrating nix.dev (which is currently a costly burden for @domenkozar )

**Comment by vcunat** [comment]
Related: I'd personally like DNSSEC turned on, though practical impact is probably negligible.

**Comment by zimbatm** [comment]
We have the Gandi org, next step: transfer the domains. @edolstra I will need your help for this.

**Comment by zimbatm** [comment]
Eelco said he doesn't have time for this week. To be continued.

**Comment by alyssais** [comment]
Any update here?
