### ISSUE TITLE
Google Season of Docs - Budget

### ISSUE THREAD

**Issue by refroni** [NixOS/foundation#54]
https://github.com/NixOS/nix.dev/blob/master/maintainers/google-season-of-docs-2023.md

**Comment by refroni** [comment]
Recapping status from foundation side -> We are working on a formal approval from the foundation which will hopefully be done by Tuesday.
Putting it in writing as well, as this is urgent and critical I've given assurance that if needed flox/me will provide the funding gap so we are unblocked.

**Comment by thufschmitt** [comment]
Application was sent and rejected (see https://github.com/NixOS/foundation/issues/48)
