### ISSUE TITLE
Apply to Docker Open Source Program

### ISSUE THREAD

**Issue by refroni** [NixOS/foundation#55]
Made the application at https://www.docker.com/community/open-source/application/
Will update once they reach back. Current timeline seems to be a few weeks.

**Comment by zimbatm** [comment]
@garbas already applied. To be continued...

**Comment by garbas** [comment]
I didn't receive any feedback so far, I've used `webmaster@nixos.org` email.

**Comment by thufschmitt** [comment]
@refroni @garbas was there any reply here?

**Comment by garbas** [comment]
Didn't receive any reply

**Comment by refroni** [comment]
I'll check in again with folks internally at Docker as well.

**Comment by thufschmitt** [comment]
FWIW, we the Foundation got an email last week (about DockerCon) mentioning
us as “a valued member of the Docker-Sponsored Open Source program”. So
unless it refers to a different thing, I assume our application got
somewhat taken into account.
