### ISSUE TITLE
Publish Nix Financials and Budget to Community

### ISSUE THREAD

**Issue by refroni** [NixOS/foundation#56]
Create a public report that covers all the donations and expenses operated by the NixOS foundation that is shared with the community.
The goal is part of our larger effort to make more parts of the foundation transparent.

**Comment by refroni** [comment]
This will also support financial planning aimed at contributing funds directly to community efforts while keeping a reserve for any potential problematic situations that will allow us to keep Nix up and running.

**Comment by zimbatm** [comment]
Making good progress. Ron showed us the high-level breakdown today.

**Comment by thufschmitt** [comment]
Closing as https://discourse.nixos.org/t/nixos-foundations-financial-summary-a-transparent-look-into-2022/28107 was published
