### ISSUE TITLE
Hire an admin person to handle all the busy work

### ISSUE THREAD

**Issue by thufschmitt** [NixOS/foundation#63]
Hire someone (a few hours/week for starters) to handle all the busy work of the foundation and allow the board and community teams to concentrate on longer-terms topics

**Comment by zimbatm** [comment]
There are a lot of good candidates on Upwork. That would avoid the administrative payroll overhead. Eg:
* https://www.upwork.com/freelancers/~01abe29594908deb25
* https://www.upwork.com/freelancers/~0170ad9f765be71c73

**Comment by zimbatm** [comment]
Next up: finish the application

**Comment by zimbatm** [comment]
Looking for feedback on the job application: https://nixos-foundation.notion.site/Part-Time-Administrative-Assistant-for-the-NixOS-Foundation-77a28f4f560749a0a6c78c8248b1fe92

**Comment by zimbatm** [comment]
This is done! :)
