### ISSUE TITLE
Get Bitwarden account for password management

### ISSUE THREAD

**Issue by zimbatm** [NixOS/foundation#74]
We need a better way than `pass` to share passwords.

**Comment by zimbatm** [comment]
I am in contact with their sales, and got this reply:

>  Of course and we do have a non-profit discount of 25% off our Teams and Enterprise licensing.

**Comment by garbas** [comment]
> /cc @NixOS/marketing - how many members do you have?

- [ ] @idabzo
- [ ] @bryanhonof
- [ ] @djacu
- [ ] @tomberek
- [ ] @garbas
- [ ] @GuillaumeDesforges 
- [ ] @Kranzes

+ 2 more but I don't have their github handles at the moment.

**Comment by zimbatm** [comment]
Is it worth paying for all those accounts for shared credentials, or can we delegate it to the marketing leader(s)?

**Comment by garbas** [comment]
I thought this is the point of this to make it easier to share the credentials with the team (even between teams). I'm not sure I would want to have this account otherwise really or to put it differently, I don't think I will remember to use it since I will be sharing the access/credentials via other means.

**Comment by garbas** [comment]
Is there any progress on this and how should we handle credentials?

**Comment by zimbatm** [comment]
@garbas can you DM me all the emails that belong to the marketing team?

**Comment by thufschmitt** [comment]
It looks like most of the team members got access. Is there anything more to be done here?

**Comment by zimbatm** [comment]
Let's close the issue once @edolstra and @domenkozar have activated their account. We can then start transferring the passwords that we have in the private "pass" repo and deprecate that.

**Comment by domenkozar** [comment]
I have created the account, but the invitation link has expired.

**Comment by zimbatm** [comment]
Re-sent all pending invites

**Comment by domenkozar** [comment]
Done.
