### ISSUE TITLE
2023-04-27: Nix/NixOS Parisian meetup at Ecole Normale Supérieure

### ISSUE THREAD

**Issue by JulienMalka** [NixOS/foundation#80]
### Event Name

Nix Parisian Meetup

### Event Website

https://mobilizon.fr/events/ebe86d0c-44f9-4ccb-a7fa-607f96c9600f

### Event Purpose

Casual Nix/NixOS meetup in Paris. Few presentations and then discussions, etc.

### Event Visitors

17

### Event Organizer

Julien Malka

### Budget amount

205,41€

### Budget description

- The money founded drinks, snacks and pizzas.

**Comment by refroni** [comment]
Approved :)

**Comment by zimbatm** [comment]
@JulienMalka, the last step is to submit the expense to https://opencollective.com/nixos/expenses/new .

**Comment by JulienMalka** [comment]
@zimbatm done already !

**Comment by JulienMalka** [comment]
Expense has been paid, thanks !
