### ISSUE TITLE
[Funding]: Oceansprint (16.10 - 20.10)

### ISSUE THREAD

**Issue by domenkozar** [NixOS/foundation#84]
### Event Name

OceanSprint 2023

### Event Website

https://oceansprint.org/

### Event Purpose

The purpose is to hack on Nix related things that folks otherwise wouldn't be able to hack on during their normal working hours.

We'll provide everything so that the folks can focus on hacking and having fun.

This kind of events lower the barrier to get their people into the Nix community and get to work with other developers.

### Event Visitors

20-25

### Event Organizer

Nejc Zupan, Domen Kožar, Florian Friesdorf

### Budget amount

2500 EUR

### Budget description

We're aiming for 15000 EUR in total, which mainly goes for catering (cca 7k) and the few activities we make (see oceansprint.org for the full list). With any remaining budget we cover the food for a dinner or two.

**Comment by refroni** [comment]
This has been approved during review of 6/6/2023

**Comment by zupo** [comment]
We got the money, so this can probably be closed?
