### ISSUE TITLE
[Funding]: Nix @ 20: An introduction and celebration (2023-06-29)

### ISSUE THREAD

**Issue by colindean** [NixOS/foundation#85]
### Event Name

Nix @ 20: An introduction and celebration

### Event Website

https://www.meetup.com/pittsburgh-code-supply/events/293592873/

### Event Purpose

> An introduction to nix, nixpkgs, nixos, plus a Nix install party, inspired by Nix's 20th anniversary.

> Matt McHenry and Samuel Eisenhandler will present on Nix and help folks get started with NixOS, a Linux distribution that uses the Nix package manager for declarative configuration.

### Event Visitors

20

### Event Organizer

Matt McHenry and Samuel Eisenhandler, and Code & Supply

### Budget amount

150 USD

### Budget description

We want to offer some healthy food, like sandwiches from Jimmy John's or light catering fare from a nearby restaurant (Chipotle, Piada [Italian-style Chipotle-esque], or Choolaah [Indian-style Chipotle-esque]). We have a no-pizza rule with an exception for huge groups.

**Comment by domenkozar** [comment]
Approved on the last board meeting.

**Comment by colindean** [comment]
@domenkozar What are the next steps in this?

**Comment by domenkozar** [comment]
Apply for reimbursement via opencollective.com/nixos

**Comment by colindean** [comment]
Thank you!

**Comment by colindean** [comment]
I've submitted on OC. Thank you!
