### ISSUE TITLE
[Funding]: 2nd Nix Israel Meetup - 2023-07-12

### ISSUE THREAD

**Issue by Kranzes** [NixOS/foundation#89]
### Event Name

The 2nd Nix Meetup in Israel

### Event Website

https://israel.nix.ug

### Event Purpose

The purpose of the event is to increase adoption of Nix in Israel by having a place for Nix users to meet up, hack together, and chat about new things related to Nix and more.

### Event Visitors

10~

### Event Organizer

Ilan Joselevich

### Budget amount

900 NIS/ILS

### Budget description

- Food
- Drinks

**Comment by refroni** [comment]
Approved :)
