### ISSUE TITLE
[Funding]: 1st Socal Nix User Group - 2023-05-30

### ISSUE THREAD

**Issue by sarcasticadmin** [NixOS/foundation#91]
### Event Name

1st Socal Nix User Group Meetings

### Event Website

https://matrix.to/#/#socal-nug:matrix.org

### Event Purpose

Southern California Nix User Group's first meeting that took place 5/30/23 in Fullerton, CA, USA @ 23b hacker space.

### Event Visitors

8

### Event Organizer

Rob Hernandez

### Budget amount

112.47

### Budget description

- Pizza
- Drinks

**Comment by refroni** [comment]
Approved :) 
If you ever have pictures let us know, we would love to share Nix meetups on the various community channels
