### ISSUE TITLE
[Funding]: froscon 5-6.8.2023

### ISSUE THREAD

**Issue by n00b0ss** [NixOS/foundation#94]
### Event Name

Froscon 

### Event Website

https://froscon.org/

### Event Purpose

Hi,

i allready wrote an email to the foundation(7.7.2023). Sadly i got no answer:(

my email:
"Dear members of the NixOS Foundation!

some members of the [c3d2 hackspace](https://c3d2.de/), including me and [Sandro](https://github.com/SuperSandro2000), are planning an Exhibition stand and a devroom  at [froscon 2023](https://froscon.org/) (an open source linux conference during August).
Unfortunately there are no nix user groups in western Germany.
We also have not seen other people who registered something about NixOS.

We were wondering if the foundation would be willing to sponsor advertisement supplies.

Here are a few things we think would be pretty nice to have:

2 Roll Up Displays
    One with just the NixOS logo
    One with the "Reproducible, Declarative, Reliable" tagline from the nixos.org website

1 NixOS Banner

NixOS stickers (with 3 different designs) as goodies
    We haven't confirmed the quantity yet, but we'll get that sorted soon

The advertising material shall not necessarily remain in our ownership but can also be passed on to others nix-enthusiast for other events.

I don't know if there is budget for it, but we would appreciate to get some support with the travel expenses. (its about 650 kilometers from dresden to froscon)

Happy Hacking,

Basti n00b0ss"

We allready bought 2 rollup displays for about 130 €.

I know that the event is in 2 days but i hope that the event funding through this form is still possible.

Kind regards
Basti

### Event Visitors

dunno ... many

### Event Organizer

Free and Open Source Software Conference (FrOSCon) e.V.

### Budget amount

500 €

### Budget description

Money for the rollup displays and maybe for some gas to get there.

**Comment by n00b0ss** [comment]
Hi, thanks for approving the 130 € . I requested more than 130 € for the case that refund for gas is possible.
It is also okay if refund for gas is not possible, i just wanted to have asked.

**Comment by edolstra** [comment]
Hi @n00b0ss, how much was the gas?

**Comment by edolstra** [comment]
Thanks, can you create another expense for that on OpenCollective?

**Comment by zimbatm** [comment]
We also want to use these events to boost our social media presence. Did you end up publishing about the event?

**Comment by domenkozar** [comment]
Who's the contact person that has the rollups now?
