### ISSUE TITLE
[Funding]: 3rd Israel Nix Meetup 2023-08-28

### ISSUE THREAD

**Issue by Kranzes** [NixOS/foundation#97]
### Event Name

The 3rd Nix Meetup in Israel

### Event Website

https://israel.nix.ug

### Event Purpose

The purpose of the event is to increase adoption of Nix in Israel by having a place for Nix users to meet up, hack together, and chat about new things related to Nix and more.

### Event Visitors

8

### Event Organizer

Ilan Joselevich

### Budget amount

300 ILS

### Budget description

Food

**Comment by refroni** [comment]
Approved
