### ISSUE TITLE
[Funding]: 3rd Socal Nix User Group - 2023-09-19

### ISSUE THREAD

**Issue by sarcasticadmin** [NixOS/foundation#98]
### Event Name

Socal Nix User Group

### Event Website

https://socal-nug.com/

### Event Purpose

We're a vibrant community centered around the Nix ecosystem. This group is for you if you're an experienced Nix developer, a Linux enthusiast, or someone who loves learning about cutting-edge technology!

Our meetups are a forum for sharing knowledge, discussing challenges, and celebrating success within the world of Nix. We delve into topics such as package management, reproducible builds, and more.

### Event Visitors

10

### Event Organizer

Rob Hernandez, Daniel Baker, David Nuon

### Budget amount

$200

### Budget description

Food and drinks

**Comment by refroni** [comment]
Approved
